# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'JanelaSecundaria.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_JanelaSecundaria(object):
    def setupUi(self, JanelaSecundaria):
        JanelaSecundaria.setObjectName("JanelaSecundaria")
        JanelaSecundaria.resize(760, 520)
        JanelaSecundaria.setMinimumSize(QtCore.QSize(760, 520))
        self.centralwidget = QtWidgets.QWidget(JanelaSecundaria)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 60, 47, 13))
        self.label.setText("")
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(80, 30, 600, 50))
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setEnabled(True)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 301, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.GerarGraficoCol = QtWidgets.QPushButton(self.groupBox)
        self.GerarGraficoCol.setGeometry(QtCore.QRect(500, 10, 91, 31))
        self.GerarGraficoCol.setObjectName("GerarGraficoCol")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(370, 10, 91, 31))
        self.comboBox.setObjectName("comboBox")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(80, 190, 600, 50))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setEnabled(True)
        self.label_3.setGeometry(QtCore.QRect(20, 20, 381, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.GerarGraficoSet = QtWidgets.QPushButton(self.groupBox_2)
        self.GerarGraficoSet.setGeometry(QtCore.QRect(500, 10, 91, 31))
        self.GerarGraficoSet.setObjectName("GerarGraficoSet")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(80, 310, 601, 111))
        self.groupBox_3.setObjectName("groupBox_3")
        self.BotaoExibirNotas = QtWidgets.QPushButton(self.groupBox_3)
        self.BotaoExibirNotas.setGeometry(QtCore.QRect(130, 10, 311, 23))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.BotaoExibirNotas.setFont(font)
        self.BotaoExibirNotas.setObjectName("BotaoExibirNotas")
        self.LabelNotas = QtWidgets.QLabel(self.groupBox_3)
        self.LabelNotas.setGeometry(QtCore.QRect(-1, 30, 601, 81))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LabelNotas.setFont(font)
        self.LabelNotas.setText("")
        self.LabelNotas.setAlignment(QtCore.Qt.AlignCenter)
        self.LabelNotas.setObjectName("LabelNotas")
        JanelaSecundaria.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(JanelaSecundaria)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 760, 21))
        self.menubar.setObjectName("menubar")
        self.menuDados_da_lista_de_aprovados = QtWidgets.QMenu(self.menubar)
        self.menuDados_da_lista_de_aprovados.setObjectName("menuDados_da_lista_de_aprovados")
        JanelaSecundaria.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(JanelaSecundaria)
        self.statusbar.setObjectName("statusbar")
        JanelaSecundaria.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuDados_da_lista_de_aprovados.menuAction())

        self.retranslateUi(JanelaSecundaria)
        self.BotaoExibirNotas.clicked.connect(JanelaSecundaria.acharMaxMin) # type: ignore
        self.GerarGraficoCol.clicked.connect(JanelaSecundaria.graficoColunas) # type: ignore
        self.GerarGraficoSet.clicked.connect(JanelaSecundaria.graficoSetores) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(JanelaSecundaria)

    def retranslateUi(self, JanelaSecundaria):
        _translate = QtCore.QCoreApplication.translate
        JanelaSecundaria.setWindowTitle(_translate("JanelaSecundaria", "MainWindow"))
        self.groupBox.setTitle(_translate("JanelaSecundaria", "Opção 1"))
        self.label_2.setText(_translate("JanelaSecundaria", "Gráfico de coluna sobre as notas do campus"))
        self.GerarGraficoCol.setText(_translate("JanelaSecundaria", "Gerar Gráfico"))
        self.groupBox_2.setTitle(_translate("JanelaSecundaria", "Opção 2"))
        self.label_3.setText(_translate("JanelaSecundaria", "Gráfico de setores da quantidade de pessoas por centro"))
        self.GerarGraficoSet.setText(_translate("JanelaSecundaria", "Gerar Gráfico"))
        self.groupBox_3.setTitle(_translate("JanelaSecundaria", "Opção 3"))
        self.BotaoExibirNotas.setText(_translate("JanelaSecundaria", "Exibir a maior e menor nota desse SISU/UFS"))
        self.menuDados_da_lista_de_aprovados.setTitle(_translate("JanelaSecundaria", "Dados da lista de aprovados"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    JanelaSecundaria = QtWidgets.QMainWindow()
    ui = Ui_JanelaSecundaria()
    ui.setupUi(JanelaSecundaria)
    JanelaSecundaria.show()
    sys.exit(app.exec_())
